stages:
  - verify
  - build
  - package
  - doc
  - pages


variables:
  QT_VERSION: "6.9.1"
  QT_ARCH: "gcc_64"
  APP_VERSION: "${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"


check_version:
  stage: verify
  image: ubuntu:24.04

  script:
    - echo "Checking version consistency..."
    - "VERSION_IN_CODE=$(grep -oP 'project\\(.*VERSION\\s+\\K[0-9]+\\.[0-9]+\\.[0-9]+' CMakeLists.txt)"
    - "TAG_VERSION=${CI_COMMIT_TAG#v}"
    - echo "CMake version: $VERSION_IN_CODE"
    - echo "Tag version: $TAG_VERSION"
    - "if ! echo \"$CI_COMMIT_TAG\" | grep -Eq '^v[0-9]+\\.[0-9]+\\.[0-9]+$'; then echo \"ERROR: Invalid tag format\"; exit 1; fi"
    - "if [ \"$VERSION_IN_CODE\" != \"$TAG_VERSION\" ]; then echo \"ERROR: Version mismatch!\"; exit 1; fi"

  rules:
    - if: '$CI_COMMIT_TAG'



build:
  stage: build
  image: ubuntu:24.04

  cache:
    key: "qt-${QT_VERSION}-${QT_ARCH}"
    paths:
      - $HOME/Qt
      - $HOME/.ccache

  before_script:
    - apt update
    - apt install -y ccache python3-pip cmake ninja-build build-essential clang libgl1-mesa-dev libglib2.0-0 libxkbcommon0 libpulse0 libdbus-1-3 libglu1-mesa
    - export CCACHE_DIR="$HOME/.ccache"
    - export CCACHE_MAXSIZE=500M

    - pip install aqtinstall --break-system-packages

    # Install Qt if not cached
    - |
      if [ ! -d "$HOME/Qt/$QT_VERSION/$QT_ARCH" ]; then
        python3 -m aqt install-qt linux desktop $QT_VERSION linux_gcc_64 \
          -O $HOME/Qt \
          -m qtmultimedia
      fi

    # Setup Qt env
    - export QT_ROOT="$HOME/Qt/$QT_VERSION/$QT_ARCH"
    - export Qt6_DIR="$QT_ROOT/lib/cmake/Qt6"
    - export PATH="$QT_ROOT/bin:$PATH"
    - export CMAKE_PREFIX_PATH="$QT_ROOT/lib/cmake"

    - echo "QT_ROOT=$QT_ROOT"
    - echo "Qt6_DIR=$Qt6_DIR"

  script:
    - cmake -S . -B build -G Ninja -DQt6_DIR=$Qt6_DIR -DCMAKE_BUILD_TYPE=Release -DCMAKE_UNITY_BUILD=OFF -DFLUVEL_GIT_COMMIT=$CI_COMMIT_SHORT_SHA -DFLUVEL_BUILD_ORIGIN="GitLab CI"
    - cmake --build build

  after_script:
      - ccache --show-stats

  rules:
    - if: '$CI_COMMIT_BRANCH != "release" && $CI_COMMIT_TAG == null'
      changes:
        - src/**/*
        - resources/**/*
        - CMakeLists.txt
        - .gitlab-ci.yml


flatpak:
  stage: package
  image: ubuntu:24.04

  before_script:
    - apt update
    - apt install -y flatpak flatpak-builder
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    # 🔥 IMPORTANT : installer runtime + sdk
    - flatpak install -y flathub org.kde.Platform//6.9
    - flatpak install -y flathub org.kde.Sdk//6.9

  script:

    - echo "Version = ${APP_VERSION}"

    - sed -i "s/__CI_COMMIT__/$CI_COMMIT_SHORT_SHA/g" packaging/flatpak/fluvel.json

    - flatpak-builder --force-clean build-flatpak packaging/flatpak/fluvel.json
    - flatpak build-export repo build-flatpak
    - flatpak build-bundle repo fluvel-${APP_VERSION}-x86_64.flatpak org.fluvel.App

  artifacts:
    paths:
      - "*.flatpak"

  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == "release"'
      changes:
        - src/**/*
        - resources/**/*
        - packaging/flatpak/**/*
        - CMakeLists.txt
        - .gitlab-ci.yml


appimage:
  stage: package
  image: ubuntu:24.04

  cache:
    key: "qt-${QT_VERSION}-${QT_ARCH}"
    paths:
      - $HOME/Qt

  before_script:
    - apt update

    - apt install -y file wget curl rsync python3-pip cmake ninja-build build-essential clang libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev libglib2.0-0 libxkbcommon0 libxkbcommon-x11-0 libxcb1 libxcb-util1 libxcb-cursor0 libxcb-icccm4 libxcb-keysyms1 libxcb-render-util0 libxcb-image0 libxcb-xinerama0 libxcb-shape0 libxcb-randr0 libxrandr2 libpulse0 libdbus-1-3 libx11-6 libxext6 libxrender1 libxi6 libxfixes3 libxcomposite1 libxcursor1 libxdamage1 libxtst6 libsm6 libice6 libfontconfig1 libfreetype6 libegl1 libwayland-client0
    - pip install aqtinstall --break-system-packages

    # Install Qt (cache partagé avec build)
    - |
      if [ ! -d "$HOME/Qt/$QT_VERSION/$QT_ARCH" ]; then
        python3 -m aqt install-qt linux desktop $QT_VERSION linux_gcc_64 \
          -O $HOME/Qt \
          -m qtmultimedia
      fi

    # Qt env
    - export QT_ROOT="$HOME/Qt/$QT_VERSION/$QT_ARCH"
    - export PATH="$QT_ROOT/bin:$PATH"
    - export Qt6_DIR="$QT_ROOT/lib/cmake/Qt6"
    - export CMAKE_PREFIX_PATH="$QT_ROOT/lib/cmake"

    # linuxdeploy
    - mkdir -p tools
    - wget -O tools/linuxdeploy-x86_64.AppImage https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
    - wget -O tools/linuxdeploy-plugin-qt-x86_64.AppImage https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
    - chmod +x tools/*.AppImage

  script:
    - echo "Version = ${APP_VERSION}"

    # Clean env (important pour éviter mélange Qt)
    - unset LD_LIBRARY_PATH
    - unset QT_PLUGIN_PATH
    - unset QML2_IMPORT_PATH

    # Build
    - cmake --fresh -S . -B build -G Ninja -DQt6_DIR=$Qt6_DIR -DCMAKE_BUILD_TYPE=Release -DCMAKE_UNITY_BUILD=OFF -DFLUVEL_GIT_COMMIT=$CI_COMMIT_SHORT_SHA -DFLUVEL_BUILD_ORIGIN="GitLab Runner"
    - cmake --build build

    # Install into AppDir
    - mkdir -p AppDir
    - cmake --install build --prefix AppDir/usr

    # Desktop + icon
    - cp packaging/appimage/fluvel.desktop AppDir/
    - cp packaging/appimage/fluvel.png AppDir/

    # Filter Qt plugins (no TIFF)
    - mkdir -p qt-plugins
    - rsync -a "$QT_ROOT/plugins/" qt-plugins/ --exclude "imageformats/libqtiff.so*"

    - export QT_PLUGIN_PATH="$CI_PROJECT_DIR/qt-plugins"
    - export APPIMAGE_EXTRACT_AND_RUN=1
    - export LINUXDEPLOY_PLUGIN_PATH="$CI_PROJECT_DIR/tools"
    - export LD_LIBRARY_PATH="$QT_ROOT/lib:$LD_LIBRARY_PATH"

    - chmod +x tools/*.AppImage

    # Build AppImage
    - ./tools/linuxdeploy-x86_64.AppImage --appdir AppDir --executable AppDir/usr/bin/fluvel --desktop-file AppDir/fluvel.desktop --icon-file AppDir/fluvel.png --plugin qt --output appimage

    - mv *.AppImage fluvel-${APP_VERSION}-x86_64.AppImage

  artifacts:
    paths:
      - ./*.AppImage

  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == "release"'
      changes:
        - src/**/*
        - resources/**/*
        - packaging/appimage/**/*
        - CMakeLists.txt
        - .gitlab-ci.yml


.doc_rules: &doc_rules
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == "release"'
      changes:
        - src/**/*
        - docs/images/**/*
        - Doxyfile
        - README.md
        - .gitlab-ci.yml

doc:
  stage: doc
  image: ubuntu:24.04
  <<: *doc_rules

  before_script:
    - apt update
    - apt install -y doxygen graphviz

  script:
    - doxygen Doxyfile
    - mv docs/html public

  artifacts:
    paths:
      - public


pages:
  stage: pages
  dependencies:
    - doc
  <<: *doc_rules

  script:
    - echo "Deploying GitLab Pages"

  artifacts:
    paths:
      - public

