stages:
  - docker
  - build
  - package
  - doc
  - pages

variables:
  QT_VERSION: "6.9.1"
  QT_ARCH: "gcc_64"

docker-build:
  stage: docker
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  script:
    - |
      # Login registry
      docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

      IMAGE="$CI_REGISTRY_IMAGE/qt-builder:qt6.9.1"

      # Check if image exists
      EXISTS=false
      if docker manifest inspect $IMAGE > /dev/null 2>&1; then
        EXISTS=true
      fi

      # Detect changes
      CHANGED=false
      if [ -z "$CI_COMMIT_BEFORE_SHA" ]; then
        CHANGED=true
      elif git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep -q '^docker/qt-builder/'; then
        CHANGED=true
      fi

      echo "Image exists: $EXISTS"
      echo "Docker changed: $CHANGED"

      if [ "$EXISTS" = "false" ] || [ "$CHANGED" = "true" ]; then
        echo "Building Docker image..."

        docker pull $IMAGE || true

        export DOCKER_BUILDKIT=1

        docker build \
          --cache-from $IMAGE \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          -t $IMAGE \
          -f docker/qt-builder/Dockerfile \
          .

        docker push $IMAGE
      else
        echo "Skipping Docker build"
      fi

  rules:
    - if: '$CI_COMMIT_BRANCH != "release" && $CI_COMMIT_TAG == null'

build:
  stage: build
  image: $CI_REGISTRY_IMAGE/qt-builder:qt6.9.1
  needs: ["docker-build"]

  cache:
    key: build-cache
    paths:
      - .ccache

  before_script:
    - export CCACHE_DIR="$CI_PROJECT_DIR/.ccache"
    - export CC="ccache gcc"
    - export CXX="ccache g++"

  script:
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        APP_VERSION=${CI_COMMIT_TAG#v}
      else
        APP_VERSION="dev-${CI_COMMIT_SHORT_SHA}"
      fi

      echo "Version = $APP_VERSION"

      BUILD_TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S")

      cmake --fresh -S . -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_UNITY_BUILD=OFF \
        -DQt6_DIR=$Qt6_DIR \
        -DFLUVEL_BUILD_VERSION=$APP_VERSION \
        -DFLUVEL_GIT_COMMIT=$CI_COMMIT_SHORT_SHA \
        -DFLUVEL_BUILD_TIMESTAMP="$BUILD_TIMESTAMP" \
        -DFLUVEL_BUILD_ORIGIN="GitLab CI"

      cmake --build build

  rules:
    - if: '$CI_COMMIT_BRANCH != "release" && $CI_COMMIT_TAG == null'
      changes:
        - src/**/*
        - resources/**/*
        - CMakeLists.txt
        - .gitlab-ci.yml

.doc_rules: &doc_rules
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == "release"'
      changes:
        - src/**/*
        - docs/images/**/*
        - Doxyfile
        - README.md
        - .gitlab-ci.yml

doc:
  stage: doc
  image: ubuntu:24.04
  <<: *doc_rules

  before_script:
    - apt update
    - apt install -y doxygen graphviz

  script:
    - doxygen Doxyfile
    - mv docs/html public

  artifacts:
    paths:
      - public

pages:
  stage: pages
  dependencies:
    - doc
  <<: *doc_rules

  script:
    - echo "Deploying GitLab Pages"

  artifacts:
    paths:
      - public
