stages:
  - build
  - doc
  - pages

variables:
  QT_VERSION: "6.7.2"
  QT_ARCH: "gcc_64"

build:
  stage: build
  image: ubuntu:24.04

  cache:
    key: qt-cache
    paths:
      - $HOME/Qt

  before_script:
    - apt update
    - apt install -y python3-pip cmake ninja-build build-essential clang libgl1-mesa-dev libglib2.0-0 libxkbcommon0 libpulse0 libdbus-1-3 libglu1-mesa

    - pip install aqtinstall --break-system-packages

    # Install Qt if not cached
    - |
      if [ ! -d "$HOME/Qt/$QT_VERSION/$QT_ARCH" ]; then
        python3 -m aqt install-qt linux desktop $QT_VERSION linux_gcc_64 \
          -O $HOME/Qt \
          -m qtmultimedia
      fi

    # Setup Qt env
    - export QT_ROOT="$HOME/Qt/$QT_VERSION/$QT_ARCH"
    - export Qt6_DIR="$QT_ROOT/lib/cmake/Qt6"
    - export PATH="$QT_ROOT/bin:$PATH"
    - export CMAKE_PREFIX_PATH="$QT_ROOT/lib/cmake"

    - echo "QT_ROOT=$QT_ROOT"
    - echo "Qt6_DIR=$Qt6_DIR"

  script:
    - cmake -S . -B build -G Ninja -DQt6_DIR=$Qt6_DIR
    - cmake --build build

doc:
  stage: doc
  image: ubuntu:24.04

  before_script:
    - apt update
    - apt install -y doxygen graphviz

  script:
    - doxygen Doxyfile
    - mv docs/html public

  artifacts:
    paths:
      - public

  only:
    - $CI_DEFAULT_BRANCH

pages:
  stage: pages
  dependencies:
    - doc

  script:
    - echo "Deploying GitLab Pages"

  artifacts:
    paths:
      - public

  only:
    - $CI_DEFAULT_BRANCH
