set(FLUVEL_PLATFORM_DESKTOP FALSE)
set(FLUVEL_PLATFORM_MOBILE FALSE)

set(FLUVEL_PLATFORM_WINDOWS FALSE)
set(FLUVEL_PLATFORM_MACOS FALSE)
set(FLUVEL_PLATFORM_LINUX FALSE)
set(FLUVEL_PLATFORM_ANDROID FALSE)
set(FLUVEL_PLATFORM_IOS FALSE)

if(WIN32)
    set(FLUVEL_PLATFORM_WINDOWS TRUE)
    set(FLUVEL_PLATFORM_DESKTOP TRUE)

elseif(APPLE)

    if(IOS)
        set(FLUVEL_PLATFORM_IOS TRUE)
        set(FLUVEL_PLATFORM_MOBILE TRUE)
    else()
        set(FLUVEL_PLATFORM_MACOS TRUE)
        set(FLUVEL_PLATFORM_DESKTOP TRUE)
    endif()

elseif(ANDROID)
    set(FLUVEL_PLATFORM_ANDROID TRUE)
    set(FLUVEL_PLATFORM_MOBILE TRUE)

elseif(UNIX)
    set(FLUVEL_PLATFORM_LINUX TRUE)
    set(FLUVEL_PLATFORM_DESKTOP TRUE)
endif()
