name: Fluvel macOS Release

on:
  push:
    branches: [release]
    tags: ['v*']

jobs:
  macos:
    runs-on: macos-latest

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Compute version (tag ou commit)
      - name: Compute version
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
          else
            VERSION="${GITHUB_SHA::7}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION = $VERSION"

      # Setup Qt
      - name: Setup Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.2'
          host: 'mac'
          target: 'desktop'
          modules: 'qtmultimedia'

      # Configure
      - name: Configure
        run: >
          cmake -B build -S .
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}"
          -DFLUVEL_GIT_COMMIT=${{ github.sha }}
          -DFLUVEL_BUILD_ORIGIN="GitHub Actions"
          -DFLUVEL_VERSION=${{ env.VERSION }}

      # Build
      - name: Build
        run: cmake --build build --config Release

      - name: Check build dir
        run: |
          echo "=== build ==="
          ls build || true
          echo "=== build/src ==="
          ls build/src || true
          echo "=== build/src/app ==="
          ls build/src/app || true

      - name: Debug app tree
        run: find build -maxdepth 3

      - name: Resolve app path
        run: |
          APP_PATH=$(find build -name "Fluvel.app" -type d | head -n 1)

          if [ -z "$APP_PATH" ]; then
            echo "❌ Fluvel.app not found"
            find build -name "*.app"
            exit 1
          fi

          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV
          echo "Using $APP_PATH"

      - name: Check macdeployqt
        run: |
          if [ ! -x "${{ env.Qt6_DIR }}/bin/macdeployqt" ]; then
            echo "❌ macdeployqt not found"
            exit 1
          fi

      # Deploy Qt
      - name: Deploy Qt
        run: |
          "${{ env.Qt6_DIR }}/bin/macdeployqt" "${{ env.APP_PATH }}" -verbose=2 -codesign=off

      - name: Check Qt bin
        run: |
          ls "${{ env.Qt6_DIR }}/bin"

      - name: Create DMG
        run: |
          rm -rf dmg
          mkdir dmg
          cp -R "${{ env.APP_PATH }}" dmg/
          ln -s /Applications dmg/Applications
          hdiutil create Fluvel-${{ env.VERSION }}-macos.dmg -volname Fluvel -srcfolder dmg -ov -format UDZO

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fluvel-macos-${{ env.VERSION }}
          path: |
            Fluvel-${{ env.VERSION }}-macos.dmg
